Feat/social proof
instantcommerce/instant-sdk-examples pull request #1
Opened 2023-02-20 16:03 UTC by avizmarques

2023-02-22 12:31 UTC, aidana12 requested changes
Good job! I think most of the points are linked to making sure the block isn't a downgrade + certain things that were missing from the storefront block :) 

Could you base to dev btw, I think it's best we don't work on main :D

2023-02-22 12:31 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +      >
substitute the first two divs with the container component + pass all the header props (you can see how I use the the header + container on dev branch src/blocks/ProductSlider/index.tsx line 14). Each block that has a "similar" header, it should use the header component because the designs don't show all the header variations for each section. Call me if you have questions :D

2023-02-22 12:31 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +        <div className={`text-${headerAlignment}`}>
remove pretitle, title, subtitle and divider because the header component in the container does it all for you if you named all the cust. and storyblok fields right

2023-02-22 12:31 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +        <div
once you finish refactoring to use the container component, add classnames to all of the elements in this file/section. E.g. 
`<Container className="social-proof"...><div className={cx('logo-wrapper w-full flex md:flex-row items-center mt-4 md:gap-y-0", ...)} >`

the social-proof and logo-wrapper classes are present for clients that want to use css snippets to further customise the blocks

2023-02-22 12:31 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +      subtitleColor: { type: "color", label: "Header subtitle color" },
you're missing a few fields here and some in the content schema, can you check the product slider fields on the dev branch. Each header should have title, pretitle, subtitle, divider and button. Texts and divider should have overridable colors, and buttons should always have border radius, type and font weight editable. Alignement, size and button position should also be added. TL;DR copy product slider fields, I think it only has header fields + theme

2023-02-22 12:31 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +                className="max-h-8 object-contain"
I think its max height 40px? you set it to 64 :D

2023-02-22 12:31 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +              : "gap-x-6 overflow-x-auto snap-x",
Edge to edge horizontal scroll is missing

There are several ways of doing it, probably best to wrap the logo wrapper in another div + add negative margins to compensate for px-2 of the container + width calc(100% + 32px) + overflow x auto, and the div inside to have px-2. Or something of the sort :D

2023-02-22 12:53 UTC, avizmarques commented on src/blocks/SocialProof/index.tsx
> +                className="max-h-8 object-contain"
ups 🙃

2023-02-22 12:55 UTC, avizmarques commented on src/blocks/SocialProof/index.tsx
> +              : "gap-x-6 overflow-x-auto snap-x",
yep, I did it like this because I was trying to make a copy of the social proof block on our admin (which doesn't have the edge to edge). Will adjust!

2023-03-01 10:46 UTC, aidana12 requested changes
I think the final changes are we are good to go. I should have mentioned that we use BEM for classnames, my bad

2023-03-01 10:46 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +        preview: "Lorem ipsum",
Change all the text content to the one in the design, I think certain elements aren't in the design so you'll have to ask for the pretitle, subtitle and buttons

2023-03-01 10:46 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +            "logo-wrapper",
We are using BEM for classnames, so logo__wrapper, please check and update all the other classnames to it too :)

2023-03-01 10:46 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +          mobileScrollDirection === "horizontal" &&
missing className for css snippet use, don't forget to use BEM https://getbem.com/naming/

2023-03-01 10:46 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +              : "gap-x-6 px-2 md:px-0",
the last logo looks like it doesnt have padding on the right of it. Maybe if you move the `w-full overflow-x-auto snap-x` to this element it'll include the padding :D

2023-03-04 16:53 UTC, aidana12 approved these changes

2023-03-04 17:23 UTC, merged