refactor(docs): renaming for clarity
instantcommerce/instant-sdk-examples pull request #10
Opened 2023-03-10 14:52 UTC by aidana12

2023-03-13 13:05 UTC, leeuwis requested changes

2023-03-13 13:05 UTC, leeuwis commented on README.md
> +You’ll notice that all of our sections and elements have readable/targetable classnames. We have found that clients like to use custom css (themselves or through agencies) to further customise their
The classNames we add to our "no-code" blocks are mainly needed because there would be no way to otherwise change the styling, but since the SDK blocks are already coded, I wouldn't encourage people to combine it with Custom CSS, they should just change it in the block code directly (or make it customizable).

2023-03-13 13:05 UTC, leeuwis commented on README.md
> +Most of our native sections have themes to enable fast colour customisation. We have light, dark, primary, primary light and gray themes. To facilitate a similar setup in the example project we have
Didn't we want to remove the gray and primary light theme from the example blocks?

2023-03-13 13:05 UTC, leeuwis commented on README.md
> +[Development docs for the installation, running and auth ](https://docs.instantcommerce.io/developer-documentation/getting-started/start#installing-dependencies)
```suggestion
[Development docs for the installation, running and auth](https://docs.instantcommerce.io/developer-documentation/getting-started/start#installing-dependencies)
```

2023-03-13 13:05 UTC, leeuwis commented on README.md
> +This example project contains custom tailwind config, theming and components to make the code closely representative of our storefront code. We hope in the future to provide more direct access to our
```suggestion
This example project contains custom tailwind config, theming and components to make the code closely representative of our storefront code. In the future we will provide more direct access to our components and admin customization settings to increase the quality and consistency of custom SDK blocks.
```

2023-03-13 13:05 UTC, leeuwis commented on README.md
> +The `setStoreColors` helper enables easy usage of the store’s primary and grayscale colours. It can be used with tailwind’s colour utilities and/or with css variables.
Externally we use US english, so best to replace all occurrences of "Colour" with "Color" (applies to the whole readme)

```suggestion
The `setStoreColors` helper enables easy usage of the store’s primary and grayscale colors. It can be used with tailwind’s color utilities and/or with css variables.
```

2023-03-13 13:05 UTC, leeuwis commented on README.md
> +# Project Title
```suggestion
# Instant SDK examples
```
I suppose it was so people can add their own project title, but it looks a bit like we forgot to add a title

2023-03-13 13:54 UTC, BJvdA commented on README.md
> +You’ll notice that all of our sections and elements have readable/targetable classnames. We have found that clients like to use custom css (themselves or through agencies) to further customise their
I think this section should be removed

2023-03-13 13:58 UTC, aidana12 commented on README.md
> +Most of our native sections have themes to enable fast colour customisation. We have light, dark, primary, primary light and gray themes. To facilitate a similar setup in the example project we have
maybe we can call the primary light primary inverted? it's weird to have one but not the opposite of it

2023-03-13 16:31 UTC, BJvdA approved these changes

2023-03-14 12:42 UTC, leeuwis approved these changes
Readme itself looks good, we could remove the "redundant" classNames that are not being used (and not highlighted anymore) as an improvement.

2023-03-14 13:43 UTC, InstantGabe requested changes
Looks good! Just some language/readability changes 👍 LMK if you'd like to discuss any of them

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +This example project contains custom tailwind config, theming and components to make the code closely representative of our storefront code. In the future we will provide more direct access to our co
add Oxford comma: "...custom tailwind config, theming, and components to make..."

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +[Development docs for the installation, running and auth](https://docs.instantcommerce.io/developer-documentation/getting-started/start#installing-dependencies)
"Read our [documentation about installing, running, and, authenticating the SDK CLI.](https://docs.instantcommerce.io/developer-documentation/getting-started/start#installing-dependencies)"

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +Further explanations about the tailwind theme colors are below.
You can leave this out.

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +This helper fetches the store’s colors and creates new css variables. In addition these variables are assigned to primary and grayscale shades in our tailwind config (`tailwind.config.cjs`), which cr
Could you maybe describe the practical advantages to assigning variables to the shades in the tailwind config in place of stating it creates the perfect marriage?

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +Most of our native sections have themes to enable fast colour customisation. To facilitate a similar setup in the example project we have created the `setSectionTheme` helper and added 4 themes: ligh
"Most of our native sections have themes to enable fast color customization. To facilitate a similar setup in the example project, we have created the `setSectionTheme` helper and added four themes: light, primary, primary inverted and dark. In many ways it’s just like the `setStoreColors` helper, except that, when using the generated CSS variables through tailwind or CSS,  you have "theme" instead of "primary" and "gray" and you have "elements" instead of "shades"."

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +The `setStoreColors` helper enables easy usage of the store’s primary and grayscale colors. It can be used with tailwind’s colour utilities and/or with css variables.
"... with CSS variables."

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +With css variables:
"With CSS variables:"

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +This helper fetches the store’s colors and creates new css variables. In addition these variables are assigned to primary and grayscale shades in our tailwind config (`tailwind.config.cjs`), which cr
"... creates new CSS variables."

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +With css variables:
"With CSS variables:"

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +`setSectionTheme` creates css variables that reference to the store’s colors that are set by `setStoreColors`:
" `setSectionTheme` creates CSS variables that reference the store’s colors as set by `setStoreColors`:"

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +You can access the variables using setSectionTheme and passing the section’s theme to it.
"You can access the variables using setSectionTheme and passing the section’s theme to it: "

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +To view the full list of elements go to `tailwind.config.cjs line 35`. To view what store colors are assigned to what elements in what themes, check out `src/config/setSectionTheme.ts`. Feel free to
"To view which store colors are assigned to which elements in which themes, check out `src/config/setSectionTheme.ts`. Feel free to adjust this file to your liking, but keep in mind that there will be inconsistencies between the native storefront's section themes and yours if you do."

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +We have discovered that having 5 different themes is not enough for our merchants. They prefer to be able to overwrite certain or all colors of the theme, hence you’ll see our customisation schema’s
"We realized we need to facilitate setups that use more than five different themes, so that you can overwrite some or all colors of a theme. For this reason, you’ll see our customisation schemas contain a lot of color fields such as `titleColor`, `backgroundColor`, and the like, where we pass inline styles to overwrite the theme colors in this example project. For instance:”

2023-03-14 13:43 UTC, InstantGabe commented on README.md
> +This goes hand-in-hand with the section theming but is optional to do just like everything else in the example project.
"This goes hand-in-hand with section theming, but it is optional (just like everything else in this example project)."

2023-03-16 10:20 UTC, merged