refactor(content): added prev invisible content
instantcommerce/instant-sdk-examples pull request #16
Opened 2023-03-13 16:58 UTC by aidana12

@InstantGabe could you take a look at the content? Some sections in development have more content options than in the design (e.g. in the design there might not be a visible pretitle, but most sections have it), so we have some rogue content that needs to be checked. In the first commit you can see I added "new" preview content, would be good if you go over it. I've attached a screenshot of the changes I made

2023-03-13 17:01 UTC, aidana12 commented on src/blocks/Collage/index.tsx
> +        preview: "New in",
<img width="1128" alt="Screenshot 2023-03-13 at 18 00 07" src="https://user-images.githubusercontent.com/26187796/224773027-d9a31105-8844-4448-af81-13a94ba61dfa.png">

2023-03-13 17:02 UTC, aidana12 commented on src/blocks/ContentCard/index.tsx
> +        preview: "New in",
<img width="1142" alt="Screenshot 2023-03-13 at 18 00 15" src="https://user-images.githubusercontent.com/26187796/224773339-fafd4fb5-1b5e-40a3-a573-b8f47a8f8e09.png">

2023-03-13 17:03 UTC, aidana12 commented on src/blocks/ProductSlider/index.tsx
> +        preview: "Bestsellers",
<img width="1140" alt="Screenshot 2023-03-13 at 18 00 53" src="https://user-images.githubusercontent.com/26187796/224773405-b442571e-69e7-4eff-9b41-7833ac73d2ec.png">

The products will be taken from the corresponding storefront, this we cannot really change, the texts could be better though

2023-03-13 17:03 UTC, aidana12 commented on src/blocks/SocialProof/index.tsx
> +        preview: "From A to Z",
<img width="1145" alt="Screenshot 2023-03-13 at 18 01 01" src="https://user-images.githubusercontent.com/26187796/224773537-cf8126a3-46ee-4016-a45c-acee98092104.png">

2023-03-13 17:05 UTC, aidana12 commented
Other sections' content, would be good to confirm
Hero:
<img width="1140" alt="Screenshot 2023-03-13 at 18 00 39" src="https://user-images.githubusercontent.com/26187796/224773845-133ca295-c248-4714-98c9-3c376e7a0f3f.png">

Announcement banner
<img width="1145" alt="Screenshot 2023-03-13 at 18 00 00" src="https://user-images.githubusercontent.com/26187796/224773959-b1b16815-bbd4-449a-b458-e07b2f9abd54.png">

Product CTA
<img width="1142" alt="Screenshot 2023-03-13 at 17 59 53" src="https://user-images.githubusercontent.com/26187796/224774039-def4dfc1-a2f7-4012-8552-e1370924d810.png">

2023-03-15 09:14 UTC, InstantGabe requested changes
Looks good overall!

2023-03-15 09:14 UTC, InstantGabe commented on src/blocks/ContentCard/index.tsx
> +        preview: "New in",
I would go for "Just in"

2023-03-15 09:14 UTC, InstantGabe commented on src/blocks/Collage/index.tsx
> +        preview: "New in",
I would go for "Just in"

2023-03-16 09:44 UTC, merged