Feat/product cta
instantcommerce/instant-sdk-examples pull request #6
Opened 2023-03-01 15:53 UTC by avizmarques

did not include the image as bg variants, styling was getting quite messy and it would probably be better to separate that into a different block

<img width="741" alt="Screenshot 2023-03-06 at 18 06 58" src="https://user-images.githubusercontent.com/52921661/223180741-45d34568-4801-47c3-bcec-ae642ffe76d0.png">

2023-03-07 10:48 UTC, aidana12 requested changes
have you tested the block if you add it to a store? does the add to cart work? So publish block, add the block in the admin, in store's storyblok add the block to a page and try to add to cart then

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +              {product?.title}
did you ask whether the title and description should come from the product or storyblock?

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +            <Paragraph
hide this whole element if there's no product description

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +            <div
hide this whole element if there's no product price

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +            contentAlignment === "bottom" && "self-end",
![Screenshot 2023-03-07 at 11 17 27](https://user-images.githubusercontent.com/26187796/223393158-9221bdf6-13b4-4ed0-903d-303b3a3eaaf2.png)

on mobile the content alignment shouldn't influence the alignment

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +              className="product-cta__title text-theme-title"
font weight medium missing

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +              className="product-cta__price mt-1.5 text-theme-text"
font weight medium missing

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +            <Button
I wonder if this button should be disabled and have a sold out label if the item is not in stock

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +    <section className={cx("product-cta", width === "contained" && "px-2")}>
I think the block should still have a py-9? The design has it

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +  const [product, setProduct] = useState<Product>();
I think there should be fallback dummy data if the product was not found, otherwise all store's except for Bart (2) will see this, because they dont have a product with that id and variant
![Screenshot 2023-03-07 at 11 29 24](https://user-images.githubusercontent.com/26187796/223396486-f23b98ad-8bf4-4b09-a4fc-91cb20928ea4.png)

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +              {price}
this needs the use money hook from my product slider branch

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +      setPrice(variant?.price);
I don't see the price show up in the preview, I think this is supposed to be: `setPrice(variant?.node?.price);`

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +  const [product, setProduct] = useState<Product>();
so have dummy title, description and price

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +        label: "Button text",
should be translatable

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +            style={{ backgroundImage: `url(${image?.filename})` }}
preferably this should have been an image with alt text for accessibility, if it's too annoying to switch, could you add aria label with the alt text from the storyblok image and role="img"

2023-03-07 10:48 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +const productQuery = gql`
this should go into a separate file just like i did for the product slider, I think I made a folder called lib with a folder shopify in it

2023-03-08 12:56 UTC, aidana12 requested changes

2023-03-08 12:56 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +        isRequired: true,
Doeke said that the initial image should be of the product and the storyblok one overwrites it, so the isrequired should be removed and the product image updates to support both

2023-03-08 12:56 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +        preview: "",
Put preview text in so that in the admin where a specific product cannot be fetch it should fallback to this

2023-03-08 12:56 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +        preview: "",
Put preview text in so that in the admin where a specific product cannot be fetch it should fallback to this

2023-03-08 12:57 UTC, aidana12 requested changes

2023-03-08 12:57 UTC, aidana12 commented on src/lib/shopify/product.ts
> +  query getProductById($id: ID!) {
should have country and language passed just like in the products query, e.g. https://github.com/instantcommerce/instant-sdk-examples/pull/9/commits/cb1dfd523eba3b3bc8e017c6c2ece88ce9647956

2023-03-08 12:57 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +          id: `gid://shopify/Product/${id}`,
should have country and language passed just like in the products query, e.g. https://github.com/instantcommerce/instant-sdk-examples/pull/9/commits/cb1dfd523eba3b3bc8e017c6c2ece88ce9647956

2023-03-08 16:17 UTC, avizmarques commented on src/blocks/ProductCta/index.tsx
> +        isRequired: true,
oh you're right, I messed up :D

2023-03-10 10:55 UTC, aidana12 requested changes

2023-03-10 10:55 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +        preview: "This is a really fancy limited edition superb tee",
please use the content that Gabe/design provided. "Minimal black sweater"

2023-03-10 10:55 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +          "Release analytics graphical user interface prototype iPhone burn rate. Bootstrapping assets beta gamification deployment conversion seed round.",
please use the content that Gabe/design provided. "Our take on one of the classic essentials. Stylish, minimal, got-to-have."

2023-03-10 10:55 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +          "https://a.storyblok.com/f/145828/4424x3355/b22d1984af/force-majeure-ggpq78xm8t0-unsplash.jpg",
please use the content that Gabe/design provided "https://a.storyblok.com/f/145828/3360x1890/b3fc3c826b/image-2.png"

2023-03-10 10:55 UTC, aidana12 commented on src/blocks/ProductCta/index.tsx
> +            "flex-1 h-full py-5 lg:py-14 px-3",
py-14 doesn't work because there's no 14 in the tailwind config, so the style is falling back to py-5
![Screenshot 2023-03-10 at 11 51 54](https://user-images.githubusercontent.com/26187796/224297968-e74f7e56-2cf6-4c77-9503-9d13ef8f44cb.png)

2023-03-10 12:39 UTC, avizmarques commented on src/blocks/ProductCta/index.tsx
> +            "flex-1 h-full py-5 lg:py-14 px-3",
I had added it to the config, but it must have got lost in a merge

2023-03-10 17:23 UTC, aidana12 approved these changes

2023-03-10 17:23 UTC, merged